services:
  netshoot:
    image: nicolaka/netshoot  # Network debugging container
    container_name: network_debugger
    networks:
      - vulnerable-network
      - control-pane-network
      - external-network
    stdin_open: true
    tty: true
networks:
  vulnerable-network:
    external: true
  control-pane-network:
    external: true
  external-network:
    external: true