services:
  botchedbox:
    build: .
    environment:
      OPENAI_KEY: ${OPENAI_KEY}
      ANTHROPIC_KEY: ${ANTHROPIC_KEY}
    volumes:
      - .:/opt/project/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
  ollama:
    image: ollama/ollama
  #  deploy:
  #    resources:
  #      reservations:
  #        devices:
  #          - driver: nvidia
  #            count: all
  #            capabilities: [gpu]
    volumes:
      - ollama_vol:/root/.ollama
    ports:
      - "11434:11434"
volumes:
  ollama_vol:
