services:
  botchedbox:
    build: .
    volumes:
      - gvmd_socket_vol:/run/gvmd
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    networks:
      - external-network
      - vulnerable-network
      - control-pane-network

volumes:
  gvmd_socket_vol:
    external: true

networks:
  external-network:
    external: true
  vulnerable-network:
    external: true
  control-pane-network:
    external: true